create table tb_bookmark (
	id integer generated by default as identity primary key,
	url varchar(500),
	name varchar(500),
	description longvarchar,
	primary key (id)
);

-- initial data

insert into tb_bookmark (id, url, name, description)
	values (1, 'http://www.codehaus.org', 'The CodeHaus', 'The Codehaus is an open-source project repository with a strong emphasis on Java, focussed on quality components that meet real world needs. We believe in open source as a pragmatic approach to software development, and all our projects are business-friendly in terms of licensing. Enjoy your stay at the haus!');

insert into tb_bookmark (id, url, name, description)
	values (2, 'http://www.google.com', 'Gooooogle', 'Bahh! The world most famous website ever.');

insert into tb_bookmark (id, url, name, description)
	values (3, 'http://www.despair.com', 'Art of Demotivation', 'Consulting: If you''re not a part of the solution, there''s good money to be made in prolonging the problem.');

insert into tb_bookmark (id, url, name, description)
	values (4, 'http://www.happytreefriends.com', 'Happy Tree Friends', 'The Happy Tree Friends are cute, cuddly animals whose daily adventures always end up going horribly wrong. No matter how innocently their day begins, it always ends in mayhem. The ensemble cast includes Cuddles, the cutest darn rabbit you''ll ever meet, and Petunia, a sweet girl skunk always mindful to wear air freshener. Traveling through picturesque settings and speaking in a kooky language all their own, the Happy Tree Friends never know what chaos lingers just around the bend.');

insert into tb_bookmark (id, url, name, description)
	values (5, 'http://www.planearium2.de/flash/spstudio.html', 'SouthPark Studio', 'Create your own SouthPark character with this tool.');

